# Parameters related to Openstack instructure
# WARN: automatically generated by provisionning script, do not edit

# All host have same prefix
HOSTNAME_TPL="${hostname_tpl}"

# First and last id for worker node names
WORKER_FIRST_ID=1
WORKER_LAST_ID="${worker_last_id}"

# Used for ssh access
MASTER="$${HOSTNAME_TPL}master-1"

# Used for ssh access
WORKERS=$(seq --format "$${HOSTNAME_TPL}worker-%g" \
    --separator=" " "$WORKER_FIRST_ID" "$WORKER_LAST_ID")

# Used for ssh access to Kubernetes master
ORCHESTRATOR="$${HOSTNAME_TPL}orchestra-1"
