# Parameters related to Openstack instructure
# WARN: automatically generated by provisionning script, do not edit

# All host have same prefix
HOSTNAME_TPL="kube-node-"

# First and last id for worker node names
WORKER_FIRST_ID=2
WORKER_LAST_ID="3"

# Used for ssh access
MASTER="${HOSTNAME_TPL}1"

# Used for ssh access
WORKERS=$(seq --format "${HOSTNAME_TPL}%g"     --separator=' ' "$WORKER_FIRST_ID" "$WORKER_LAST_ID")

# Used for ssh access to Kubernetes master
ORCHESTRATOR="kube-master"
