# Parameters related to Openstack instructure
# WARN: automatically generated by provisionning script, do not edit

# Used for ssh access
MASTER="*"

# Used for ssh access
WORKERS="* *"

# Used for ssh access to Kubernetes master
ORCHESTRATOR="$HOSTNAME"
