apiVersion: v1
kind: Service
metadata:
  name: qserv-fe
  labels:
    app: qserv
    node: master
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: qserv 
      port: 4040
      nodePort: 30040
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: qserv
    node: master
