apiVersion: v1
kind: Service
metadata:
  name: repl-ctl
  labels:
    app: qserv
    tier: repl-ctl
spec:
  ports:
    # the port that this service should serve on
    - name: repl-ctl 
      port: 80
  selector:
    app: qserv
    tier: repl-ctl
